services:
  generic-pdf-processor:
    image: generic-pdf-processor
    build: 
      context: ./generic-pdf-processor
      target: dev
    ports:
      - 4000:4000
    volumes:
      - ./generic-pdf-processor:/app
    